[[ImageGroup]]
name = "AllImage"
defaultDir = "Resources"
isAll = true 

[[Menu]]
name = "Game"
text = "游戏"
program = ""
path = ""

[[Menu.Menu]]
name = "Steam"
text = "Steam"
program = ""
path = "E:\\Games\\Steam\\Steam.exe"

[[Menu.Menu]]
name = "UU"
text = "网易UU加速器"
program = ""
path = "E:\\Softwares\\Netease\\UU\\uu.exe"

[[Menu.Menu]]
name = "StarRail"
text = "星穹铁道"
program = ""
path = "E:\\Games\\Star Rail\\Game\\StarRail.exe"

[[Menu]]
name = "Notes"
text = "笔记"
program = ""
path = ""

[[Menu.Menu]]
name = "SuNotes"
text = "SuNotes"
program = "C:\\Program Files\\Microsoft Office\\root\\Office16\\ONENOTE.EXE"
path = "D:\\SuNotes\\打开笔记本.onetoc2"

[[Menu.Menu]]
name = "OldNotes"
text = "Notes"
program = "Explorer.exe"
path = "D:\\Notes"
